dist: xenial
language: python
notifications:
  email: false
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
sudo: false
before_install:
  # make sure we have wheel and setuptools
  - pip install -U pip wheel setuptools
  # pre install scientific wheels so we dont have to build
  #- pip install --only-binary=numpy,scipy,pandas numpy scipy pandas
install:
  - python setup.py install
script:
  # test import
  - python -c 'import donnie'
# cashe pip
cache:
  directories:
    - $HOME/.cache/pip
deploy:
  provider: pypi
  user: s4w3d0ff
  password:
    secure: "lIG4jgU7ilviM1ERFZ+wIQ+BlM48IKB0b7XX8N8oXnnyaU0Zy0cphjImepGpypwrdkiWylFQ+bOUwDybLMeqBinX/ZHs5dHIHF4wXw1R/B9STOLueckepOpjcAoxBRuCvZD22wUDIHgvUj37uAf/CPObSXD+OPMZT6gLo3ZvmQYCbGmQddO38mGY1WLM8ZQmGe8BzB2QoB7kkSp+VjCPScvEHZoC+JCXPNu7ImCLdEQdxrDOlQrp9Xz8fvUv9urSctZYFq8KHrSsNhKNZklOxHkOGU58gKjZbAIATpG13GbknmLoazpTEGZyylQR03VwjhAqQ6bkpugfKqJvO+55FVSFPk3r9eMD8s7rOch4wnH0/yV0Xp50M5cg5AG3VH1799JCRWVstv/uxHxgMskSLRWL0YdPAGfJBNtn3rIJrJN1dRGEjwMf9yHAQZtBPKLr4fmgqAmJeQuukYBILzN5KlYZK5aj53lZm07LfrVuSQxvAfHVAtweWWMz5+TgfAsid802JWQ+PqNGc0GsDYqzAaF5ntnsF095LAVHlQC8e03yflwqv9Mec9GVn0rkVPpFyuJdtVjxPf8LqbMSEoHcHKWC62NUs97d4MMEMd0loPn7gLT8b0uqoNONw+rjYROdqLHWeUiqd+K1oGS9YXhu9+AdSaQ8rMS8ATwlBcZv8p0="
  on:
    tags: true
  skip_existing: true
